name: 'Raygun - Create Deployment'
description: 'Notifies Raygun of a deployment/release'
branding:
  icon: 'zap'
  color: 'gray-dark'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  personal-access-token:
    description: 'Raygun Personal Access Token'
    required: true
  api-key:
    description: 'Raygun Application API Key'
    required: true
  version:
    description: 'Version of the application'
    required: true
  owner-name:
    description: 'Name of the owner'
    required: false
  email-address:
    description: 'Email address of the owner'
    required: false
  comment:
    description: 'Optional comment'
    required: false
outputs:
  deploymentId:
    description: 'The unique identifier for the newly created deployment'
